const emergencyContacts = [
  {
    id: 'security',
    category: 'Campus Security',
    icon: '🛡️',
    iconName: 'ShieldAlert',
    tier: 1,
    badge: '24x7 Dispatch',
    accent: 'amber',
    description: 'Immediate campus guard response & control room monitoring.',
    contacts: [
      { name: 'Security Control Room (24x7)', number: '080-1234-5679', isPrimary: true, is24x7: true },
      { name: 'Main Gate Security', number: '080-1234-5678', isPrimary: false, is24x7: false },
    ],
  },
  {
    id: 'medical',
    category: 'Medical & Ambulance',
    icon: '🚑',
    iconName: 'Ambulance',
    tier: 1,
    badge: 'Life Safety',
    accent: 'crimson',
    description: 'On-campus first aid, emergency medical triage, & rapid ambulance dispatch.',
    contacts: [
      { name: 'Ambulance (24x7)', number: '108', isPrimary: true, is24x7: true },
      { name: 'Campus Medical Room', number: '080-1234-5680', isPrimary: false, is24x7: false },
    ],
  },
  {
    id: 'womens-helpline',
    category: "Women's Helpline",
    icon: '🆘',
    iconName: 'HeartHandshake',
    tier: 1,
    badge: 'Confidential 24x7',
    accent: 'crimson',
    description: 'Immediate assistance, anti-harassment cell, & national helpline.',
    contacts: [
      { name: "Women's Safety Cell", number: '080-1234-5687', isPrimary: true, is24x7: true },
      { name: "National Women's Helpline", number: '1091', isPrimary: false, is24x7: true },
    ],
  },
  {
    id: 'fire',
    category: 'Fire & Safety',
    icon: '🔥',
    iconName: 'Flame',
    tier: 2,
    badge: 'Emergency Response',
    accent: 'amber',
    description: 'Campus fire marshals, lab safety alerts, and municipal fire services.',
    contacts: [
      { name: 'Fire Department', number: '101', isPrimary: true, is24x7: true },
      { name: 'Campus Fire Safety Officer', number: '080-1234-5681', isPrimary: false, is24x7: false },
    ],
  },
  {
    id: 'police',
    category: 'Local Police',
    icon: '🚓',
    iconName: 'Siren',
    tier: 2,
    badge: 'Law Enforcement',
    accent: 'cobalt',
    description: 'Local precinct hotline and city emergency response unit.',
    contacts: [
      { name: 'Police Emergency', number: '100', isPrimary: true, is24x7: true },
      { name: 'Nearest Police Station', number: '080-1234-5686', isPrimary: false, is24x7: false },
    ],
  },
  {
    id: 'hostel',
    category: 'Hostel & Warden',
    icon: '🏠',
    iconName: 'Home',
    tier: 2,
    badge: 'Residential Support',
    accent: 'cobalt',
    description: 'In-house hostel oversight, night curfews, and residential assistance.',
    contacts: [
      { name: 'Girls Hostel Warden', number: '080-1234-5683', isPrimary: true, is24x7: false },
      { name: 'Boys Hostel Warden', number: '080-1234-5682', isPrimary: false, is24x7: false },
    ],
  },
  {
    id: 'admin',
    category: 'Administration',
    icon: '🏢',
    iconName: 'Building2',
    tier: 3,
    badge: 'Office Hours',
    accent: 'teal',
    description: 'Dean of student affairs and central university administrative office.',
    contacts: [
      { name: 'Dean of Students', number: '080-1234-5684', isPrimary: true, is24x7: false },
      { name: 'Admin Office', number: '080-1234-5685', isPrimary: false, is24x7: false },
    ],
  },
  {
    id: 'transport',
    category: 'Transport',
    icon: '🚌',
    iconName: 'Bus',
    tier: 3,
    badge: 'Campus Shuttle',
    accent: 'teal',
    description: 'College bus schedules, route breakdown support, and transport queries.',
    contacts: [
      { name: 'College Bus Coordinator', number: '080-1234-5688', isPrimary: true, is24x7: false },
    ],
  },
];

export default emergencyContacts;
